module.exports = {
  Institucion: require('./institucion'),
  Usuario: require('./usuario'),
  AnioAcademico: require('./anioacademico'),
  Sede: require('./sede'),
  Grupo: require('./grupo'),
  Area: require('./area'),
  Asignatura: require('./asignatura'),
  CargaAcademica: require('./cargaacademica'),
  Matricula: require('./matricula'),
  Indicador: require('./indicador'),
  Actividad: require('./actividad'),
  Calificacion: require('./calificacion'),
  DireccionNucleo: require('./direccionnucleo'),
  Bitacora: require('./bitacora'),
  Observador: require('./observador'),
  Excusas: require('./excusas'),
  ConceptosContables: require('./conceptoscontables'),
  Pagos: require('./pagos'),
  Elecciones: require('./elecciones'),
  EventoElectoral: require('./eventoelectoral'),
  Voto: require('./voto'),
  Catalogo: require('./catalogo'),
  Prematricula: require('./prematricula'),
  Comunicados: require('./comunicados'),
  SolicitudRegistro: require('./solicitudregistro')
};
